### ISSUE TITLE
Read and Check Pedigree does nothing

### ISSUE THREAD

**Issue by guyinco6nito** [rmsharp/nprcgenekeepr#15]
Hello,

I'm going through the instructions here:  https://rmsharp.github.io/nprcgenekeepr/articles/ColonyManagerTutorial.html#uploading-a-pedigree-file-1

But the tool does nothing when I click "Read and Check Pedigree".  I've used the "makeExamplePedigreeFile()" tool to make an example CSV for testing, and it does not work.  I can browse to "examplePedigree.csv" but when I click "Read and Check Pedigree" nothing happens.  Turning Debug On and clicking again doesn't seem to change anything.  In the R console output, it shows the following:

runGeneKeepR()
Loading required package: shiny

Listening on http://127.0.0.1:6012

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

Warning in getSiteInfo() :
  The nprcgenekeepr configuration file is missing.
It is required when the LabKey API is to be used.
The file should be named: C:/Users/dpmetzger/Documents/_nprcgenekeepr_config.

Warning in getSiteInfo() :
  The nprcgenekeepr configuration file is missing.
It is required when the LabKey API is to be used.
The file should be named: C:/Users/dpmetzger/Documents/_nprcgenekeepr_config.

Warning in getSiteInfo() :
  The nprcgenekeepr configuration file is missing.
It is required when the LabKey API is to be used.
The file should be named: C:/Users/dpmetzger/Documents/_nprcgenekeepr_config.

Warning in getSiteInfo() :
  The nprcgenekeepr configuration file is missing.
It is required when the LabKey API is to be used.
The file should be named: C:/Users/dpmetzger/Documents/_nprcgenekeepr_config.

Warning: Error in get: object '%OR%' not found
  52: get
  51: :::
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '%OR%' not found

I've tried this using R 4.0.4 on both Windows and Mac computers, and got the same results on each.  Is there some other changes we need to make to our workstations to get this to work?

Thanks,
-Dan Metzger

**Comment by rmsharp** [comment]
Thank you very much for the note and I am sorry I have wasted some of your time due to errors I have made. Do you have time to meet with me online to help me see what is going on?

By the way, those warnings are simply that. The first is only to warn you that if you want to use dataTableOutput() or renderDataTable() from another package you will have to ensure the namespace is forced with something like
 <other package>::dataTableOutput(). The second only affects those using the package and wanting the LabKey API to fetch the animal pedigree.

I need to suppress the one from DT and limit the one from getSiteInfo to a single message. 
I have tested the functions a lot, but I have not tested my instructions! Hopefully, you will help me fix instructions and perhaps some code. You will see those tasks added as new issues.

During the next three days I have the following time slots available. It is spring break here so many of my coworkers are off and my schedule is very open. All times are Central Standard.
Tuesday: 8:30-10:00 AM, 10:30 AM - 2:00 PM, 3:30 PM - 9:00 PM
Wednesday: 12:00-1:30 PM, 2:00-9:00 PM
Thursday: 9:00-11:00 AM, 12:00-9:00 PM

I leave for vacation Friday and plan on working on nprcgenekeepr during that time as well.

You can reach me at rmsharp@me.com. Make sure to put "nprcgenekeepr" in the subject line.
Mark

**Comment by rmsharp** [comment]
Dan and I  met a few times and were able to resolve his issues.
